name: Label issues
on:

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'label: debug instead of: triage'
        required: true
        type: boolean

  
jobs:
  label-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues
        uses: andymckay/labeler@1.0.2
        if: ${{ inputs.logLevel }}
        with:
          add-labels: "triage"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Label issues with debug
        uses: andymckay/labeler@1.0.2
        if: ${{ !inputs.logLevel }}
        with: 
          add-labels: "debug"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
