name: Label issues
on:

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'label: debug instead of: triage'
        required: true
        type: boolean

  
jobs:
  label-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues
        uses: andymckay/labeler@1.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          if: ${{ inputs.logLevel }}
          add-labels: "triage"
         
