name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      print_tags:
        description: 'True to print to STDOUT'
        required: true 
        type: boolean 


  
jobs:
  label-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: "triage"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
