name: install-netlify-package
on:
  workflow_dispatch:
    
jobs:
  check-netlify-versions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3.4.1
    - run: npm install netlify-cli -g
    - run: npm netlify -v
